# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectStructer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectStructer
    pod 'SDWebImage', '~> 4.0'  # Image Load Pod
    pod 'Alamofire', '~> 4.7'   # API Calling Pod
  target 'ProjectStructerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectStructerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
